### ISSUE TITLE
#9 Backlog, Add planned games for specific season within turns

### ISSUE THREAD

**Issue by danielw15** [alexfristrom/sportstats#3]
9 Lägg till planerade matcher för specifik säsong och inom omgångar (en säsong skall inte kunna innehålla fler omgångar än avsett och i en omgång kan ett lag bara ha en match)

**Comment by Sjoblompwr** [comment]
[5ded15b](https://github.com/alexfristrom/sportstats/commit/5ded15ba20b1c94cf5852af8f33fd011e451dc6d)
